services:
  mongo:
    image: mongo:7.0.5
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: course-service
    volumes:
      - ./docker/mongodb/data:/data/db
    networks:
      - onlinelearning-network

  mysql:
    image: mysql:8.3.0
    container_name: mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 12345
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
    networks:
      - onlinelearning-network

  course-service:
    image: course-service
    build:
      context: ./course
      dockerfile: Dockerfile
    environment:
      SPRING_DATA_MONGODB_HOST: mongo
      SPRING_DATA_MONGODB_DATABASE: courseservice 
      MONGO_PORT: 27017
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    networks:
      - onlinelearning-network

  coursetests-service:
    image: coursetests-service
    build:
      context: ./courseTests
      dockerfile: Dockerfile
    environment:
      SPRING_DATA_MONGODB_HOST: mongo
      SPRING_DATA_MONGODB_DATABASE: testsservice 
      MONGO_PORT: 27017
    ports:
      - "8081:8081"
    depends_on:
      - mongo
    networks:
      - onlinelearning-network

  api-gateway-service:
    image: api-gateway-service
    build:
      context: ./api-geteway
      dockerfile: Dockerfile
    environment:
      COURSES_URL: http://course-service:8080
      TESTS_URL: http://coursetests-service:8081
    ports:
      - "9000:9000"
    networks:
      - onlinelearning-network

  keycloak-mysql:
    container_name: keycloak-mysql
    image: mysql:8
    ports:
    - "3308:3306"
    volumes:
    - ./docker/mysql_keycloak/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: keycloak
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: 12345
    networks:
    - onlinelearning-network

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:24.0.1
    command: [ "start-dev", "--import-realm" ]
    environment:
      KC_DB: mysql
      KC_DB_URL: jdbc:mysql://keycloak-mysql:3306/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: 12345
      KEYCLOAK_ADMIN: sprigg4n-
      KEYCLOAK_ADMIN_PASSWORD: Romashka28
    ports:
    - "8181:8080"
    volumes:
    - ./docker/keycloak/realms/:/opt/keycloak/data/import/
    depends_on:
    - keycloak-mysql
    networks:
    - onlinelearning-network

networks:
  onlinelearning-network:
    driver: bridge
